version: '3.8'

services:
  backend:
    image: ${AWS_ECR_REGISTRY:-375291783713.dkr.ecr.us-east-1.amazonaws.com}/${ECR_REPOSITORY_BACKEND:-infragen-api}:${IMAGE_TAG:-latest}
    container_name: infragen_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3011:3001"